In [2]:
import torch

In [3]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [4]:
a[1]

tensor(1.)

In [5]:
float(a[1])

1.0

In [6]:
points = torch.zeros(6)
points

tensor([0., 0., 0., 0., 0., 0.])

In [7]:
points = torch.tensor([1,2,3,4,5,6])
points

tensor([1, 2, 3, 4, 5, 6])

In [8]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [9]:
points.shape

torch.Size([3, 2])

In [10]:
points[0,1]

tensor(1.)

In [11]:
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])
weights_named

/var/folders/20/z3524q651yg27lmbdsqklkrr0000gn/T/ipykernel_5881/2371314847.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1670525849783/work/c10/core/TensorImpl.h:1761.)
  weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=['channels'])


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [12]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [13]:
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])