In [3]:
import torch.nn as nn
import torch

In [4]:
linear_model = nn.Linear(1, 1)
t_un_val = torch.tensor([[1.0], [2.0], [3.0]])
linear_model(t_un_val)

tensor([[-0.0123],
        [-0.5981],
        [-1.1839]], grad_fn=<AddmmBackward0>)

In [8]:
linear_model.weight

Parameter containing:
tensor([[-0.5858]], requires_grad=True)

In [9]:
linear_model.bias

Parameter containing:
tensor([0.5735], requires_grad=True)

In [11]:
import torch.optim as optim

In [12]:
linear_model = nn.Linear(1, 1)
optimizer = optim.SGD(
    linear_model.parameters(),
    lr=1e-2)

In [13]:
linear_model.parameters()

<generator object Module.parameters at 0x1228c6ba0>

In [14]:
list(linear_model.parameters())

[Parameter containing:
 tensor([[-0.7528]], requires_grad=True),
 Parameter containing:
 tensor([-0.7130], requires_grad=True)]

In [17]:
def training_loop(n_epochs, optimizer, model, loss_fn, t_u_train, t_u_val,
              t_c_train, t_c_val):
    for epoch in range(1, n_epochs + 1):
        t_p_train = model(t_u_train)
        loss_train = loss_fn(t_p_train, t_c_train)
        
    t_p_val = model(t_u_val)
    loss_val = loss_fn(t_p_val, t_c_val)

    optimizer.zero_grad()
    loss_train.backward()
    optimizer.step()

    if epoch == 1 or epoch % 1000 == 0:
        print(f"Epoch {epoch}, Training loss {loss_train.item():.4f},"
                f" Validation loss {loss_val.item():.4f}")


In [18]:
linear_model = nn.Linear(1, 1)
optimizer = optim.SGD(linear_model.parameters(), lr=1e-2)

In [23]:
# 需要.unsqueeze(1)才能成功运行
t_un_train = torch.tensor([0.1 * i for i in range(14)]).unsqueeze(1)
t_un_val = torch.tensor([0.1 * i for i in range(14, 20)]).unsqueeze(1)
t_c_train = torch.tensor([0.1 * i for i in range(14)]).unsqueeze(1)
t_c_val = torch.tensor([0.1 * i for i in range(14, 20)]).unsqueeze(1)

In [22]:
training_loop(
    n_epochs = 3000,
    optimizer = optimizer,
    model = linear_model,
    loss_fn = nn.MSELoss(),
    t_u_train = t_un_train,
    t_u_val = t_un_val,
    t_c_train = t_c_train,
    t_c_val = t_c_val)
    
print()
print(linear_model.weight)
print(linear_model.bias)

Epoch 3000, Training loss 3.3972, Validation loss 11.4112

Parameter containing:
tensor([[-0.6192]], requires_grad=True)
Parameter containing:
tensor([-0.6146], requires_grad=True)


In [24]:
seq_model = nn.Sequential(
    nn.Linear(1, 13),
    nn.Tanh(),
    nn.Linear(13, 1)
)

seq_model

Sequential(
  (0): Linear(in_features=1, out_features=13, bias=True)
  (1): Tanh()
  (2): Linear(in_features=13, out_features=1, bias=True)
)